export const POKEMONS = [
  {
    name: "Pikachu",
    type: "electric",
    hp: 274,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png",
    lvl: 1,
    attacks: [
      {
        name: "thunder jolt",
        maxDamage: 40,
        minDamage: 20,
        maxCount: 100,
        id: 1,
      },
      {
        name: "electro ball",
        maxDamage: 60,
        minDamage: 45,
        maxCount: 6,
        id: 2,
      },
      {
        name: "volt tackle",
        maxDamage: 75,
        minDamage: 60,
        maxCount: 4,
        id: 3,
      },
      {
        name: "thunder crack",
        maxDamage: 160,
        minDamage: 130,
        maxCount: 2,
        id: 4,
      },
    ],
  },
  {
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png",
    name: "Charmander",
    type: "fire",
    hp: 282,
    lvl: 1,
    attacks: [
      {
        name: "ember",
        maxDamage: 40,
        minDamage: 20,
        maxCount: 100,
        id: 5,
      },
      {
        name: "flamethrower",
        maxDamage: 60,
        minDamage: 45,
        maxCount: 6,
        id: 6,
      },
      {
        name: "burning tail",
        maxDamage: 75,
        minDamage: 60,
        maxCount: 4,
        id: 7,
      },
      {
        name: "fire spin",
        maxDamage: 130,
        minDamage: 110,
        maxCount: 2,
        id: 8,
      },
    ],
  },
  {
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png",
    name: "Bulbasaur",
    type: "grass",
    hp: 294,
    lvl: 1,
    attacks: [
      {
        name: "tackle",
        maxDamage: 40,
        minDamage: 20,
        maxCount: 100,
        id: 9,
      },
      {
        name: "vine whip",
        maxDamage: 60,
        minDamage: 45,
        maxCount: 6,
        id: 10,
      },
      {
        name: "razor leaf",
        maxDamage: 75,
        minDamage: 60,
        maxCount: 4,
        id: 11,
      },
      {
        name: "solar beam",
        maxDamage: 130,
        minDamage: 110,
        maxCount: 2,
        id: 12,
      },
    ],
  },
  {
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png",
    name: "Squirtle",
    type: "water",
    hp: 292,
    lvl: 1,
    attacks: [
      {
        name: "bubble",
        maxDamage: 40,
        minDamage: 20,
        maxCount: 100,
        id: 13,
      },
      {
        name: "water gun",
        maxDamage: 60,
        minDamage: 45,
        maxCount: 6,
        id: 14,
      },
      {
        name: "shell attack",
        maxDamage: 75,
        minDamage: 60,
        maxCount: 4,
        id: 15,
      },
      {
        name: "hydro pump",
        maxDamage: 130,
        minDamage: 110,
        maxCount: 2,
        id: 16,
      },
    ],
  },
  {
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png",
    name: "Pidgey",
    type: "air",
    hp: 284,
    lvl: 1,
    attacks: [
      {
        name: "Air Slash",
        maxDamage: 40,
        minDamage: 20,
        maxCount: 100,
        id: 17,
      },
      {
        name: "Razor Wind",
        maxDamage: 60,
        minDamage: 45,
        maxCount: 6,
        id: 18,
      },
      {
        name: "Heat Wave",
        maxDamage: 75,
        minDamage: 60,
        maxCount: 4,
        id: 19,
      },
      {
        name: "Sky Attack",
        maxDamage: 130,
        minDamage: 110,
        maxCount: 2,
        id: 20,
      },
    ],
  },
  {
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/151.png",
    name: "Mew",
    type: "air",
    hp: 404,
    lvl: 1,
    attacks: [
      {
        name: "Pound",
        maxDamage: 40,
        minDamage: 20,
        maxCount: 100,
        id: 21,
      },
      {
        name: "Ancient Power",
        maxDamage: 60,
        minDamage: 45,
        maxCount: 6,
        id: 22,
      },
      {
        name: "Aura Sphere",
        maxDamage: 75,
        minDamage: 60,
        maxCount: 4,
        id: 23,
      },
      {
        name: "Psychic",
        maxDamage: 130,
        minDamage: 110,
        maxCount: 2,
        id: 24,
      },
    ],
  },
]
